name: b2b_governo
description: "Plataforma de dados de consumo de energia em Pernambuco."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/icon/b2b_governo.png 

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/b2b_governo.png"

  adaptive_icon_background: "#FF6D00"   # mesma cor do app (laranja)
  adaptive_icon_foreground: "assets/icon/b2b_governo.png"