// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRP0q7l0Gdj59sFzq3xRgLAvWd_nLPGQ',
    appId: '1:1077991053183:web:325708c58f196193ffac4a',
    messagingSenderId: '1077991053183',
    projectId: 'flutterapp-b57a2',
    authDomain: 'flutterapp-b57a2.firebaseapp.com',
    storageBucket: 'flutterapp-b57a2.firebasestorage.app',
    measurementId: 'G-K0FXXLCH6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4MaUayyZwfs9U53Tgm93bJNxgdUdp760',
    appId: '1:1077991053183:android:21a35774b3cb38beffac4a',
    messagingSenderId: '1077991053183',
    projectId: 'flutterapp-b57a2',
    storageBucket: 'flutterapp-b57a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4oJQK6t4uF4qZd4ENQaS6mSWVCvZdkfU',
    appId: '1:1077991053183:ios:c6e4cfac05ddf220ffac4a',
    messagingSenderId: '1077991053183',
    projectId: 'flutterapp-b57a2',
    storageBucket: 'flutterapp-b57a2.firebasestorage.app',
    iosBundleId: 'com.example.twitterLoginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4oJQK6t4uF4qZd4ENQaS6mSWVCvZdkfU',
    appId: '1:1077991053183:ios:c6e4cfac05ddf220ffac4a',
    messagingSenderId: '1077991053183',
    projectId: 'flutterapp-b57a2',
    storageBucket: 'flutterapp-b57a2.firebasestorage.app',
    iosBundleId: 'com.example.twitterLoginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtRP0q7l0Gdj59sFzq3xRgLAvWd_nLPGQ',
    appId: '1:1077991053183:web:5bd954e086625299ffac4a',
    messagingSenderId: '1077991053183',
    projectId: 'flutterapp-b57a2',
    authDomain: 'flutterapp-b57a2.firebaseapp.com',
    storageBucket: 'flutterapp-b57a2.firebasestorage.app',
    measurementId: 'G-HBLC6YZYC4',
  );

}